services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["prod", "dev"]

  web:
    build: .
    container_name: django_web_prod
    command: /app/.venv/bin/gunicorn django_base.wsgi:application --bind 0.0.0.0:8000
    profiles: ["prod"]
    volumes:
      - ./src:/app/src
      - venv_data:/app/.venv
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    environment:
      - PYTHONPATH=/app/src
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      db:
        condition: service_healthy

  qcluster:
    build: .
    container_name: django_qcluster
    command: /app/.venv/bin/python manage.py qcluster
    profiles: ["prod", "dev"]
    volumes:
      - ./src:/app/src
      - venv_data:/app/.venv
    environment:
      - PYTHONPATH=/app/src
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      web:
        condition: service_started
      db:
        condition: service_healthy

  nginx:
    build: ./nginx
    container_name: nginx
    profiles: ["prod"]
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:80"
    depends_on:
      - web

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles: ["prod", "dev"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - web

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    profiles: ["prod", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
  venv_data:
  prometheus_data:
  static_volume:
  media_volume: