[project]
name = "django-base"
version = "0.1.0"
description = "Base para um projeto Django / Base for a Django project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "databases>=0.5.5",
    "django>=5.2.7",
    "django-cors-headers>=4.9.0",
    "django-prometheus>=2.4.1",
    "django-q2>=1.8.0",
    "djangorestframework>=3.16.1",
    "gunicorn>=23.0.0",
    "ormar>=0.10.23",
    "psycopg2-binary>=2.9.10",
    "python-decouple>=3.8",
    "sqlalchemy>=1.3.24,<1.4",
]

[tool.setuptools]
packages = { find = { where = ["src"] } }

# Ruff Linter and Formatter Configuration
# Configuração do Linter e Formatador Ruff
[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP", "B", "C4"]
ignore = []

# Coverage.py Configuration
# Configuração do Coverage.py
[tool.coverage.run]
source = ["core"]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "*/admin.py",
    "manage.py",
    "django_base/*",
]

[tool.coverage.report]
show_missing = true

[dependency-groups]
dev = [
    "coverage>=7.10.7",
    "django-extensions>=4.1",
    "pre-commit>=4.3.0",
    "ruff>=0.13.2",
    "watchdog>=6.0.0",
    "werkzeug>=3.1.3",
]

[project.optional-dependencies]
dev = [
    "coverage>=7.5.0",
    "django-extensions>=3.2.0",
    "pre-commit>=3.7.0",
    "ruff>=0.4.0",
    "watchdog>=4.0.0",
    "werkzeug>=3.0.0",
]
