[project]
name = "django-base"
version = "0.1.0"
description = "Base para um projeto Django"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.7",
    "django-q2>=1.8.0",
    "psycopg2-binary>=2.9.10",
    "python-decouple>=3.8",
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP", "B", "C4"]
ignore = []

[tool.coverage.run]
source = ["core"]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "*/admin.py",
    "manage.py",
    "django_base/*",
]

[tool.coverage.report]
show_missing = true

[dependency-groups]
dev = [
    "coverage>=7.10.7",
    "pre-commit>=4.3.0",
    "ruff>=0.13.2",
]
