# Generated by Django 5.2.7 on 2025-10-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # noqa: RUF012

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the product (max 100 characters) / O nome do produto (máximo 100 caracteres)",
                        max_length=100,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Product price in currency units / Preço do produto em unidades monetárias",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the product was created / Timestamp de quando o produto foi criado",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the product was last updated / Timestamp da última atualização do produto",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indicates if the product is active (soft delete) / Indica se o produto está ativo (soft delete)",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_deactivate_product", "Can deactivate product"),
                    ("can_set_special_price", "Can set special pricing"),
                ],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"], name="active_created_idx"
                    ),
                    models.Index(fields=["name"], name="name_idx"),
                    models.Index(fields=["price"], name="price_idx"),
                ],
            },
        ),
    ]
