# Generated by Django 5.2.7 on 2025-10-21 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_category_core_catego_is_acti_26a709_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_delete_product", "Can soft delete product"),
                    ("can_set_special_price", "Can set special pricing"),
                ],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="core_catego_is_acti_26a709_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="active_created_idx",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.AddField(
            model_name="category",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the record was deleted",
                null=True,
                verbose_name="Deleted At",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if the record is soft deleted",
                verbose_name="Is Deleted",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the record was deleted",
                null=True,
                verbose_name="Deleted At",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if the record is soft deleted",
                verbose_name="Is Deleted",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                default=0,
                help_text="Product stock quantity / Quantidade em estoque do produto",
                verbose_name="Stock",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="The name of the product (max 200 characters) / Nome do produto (máx 200 caracteres)",
                max_length=200,
                verbose_name="Product Name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Product price in currency units / Preço do produto em unidades monetárias",
                max_digits=10,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Product tags / Tags do produto",
                related_name="products",
                to="core.tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_deleted"], name="core_catego_is_dele_3393a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_deleted", "-created_at"], name="deleted_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["stock"], name="stock_idx"),
        ),
    ]
