# Generated by Django 5.2.7 on 2025-10-07 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("core", "0002_tag_product_created_by_category_product_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Category description / Descrição da categoria",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Active status / Status ativo",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category name (unique) / Nome da categoria (único)",
                max_length=100,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category for hierarchical structure / Categoria pai para estrutura hierárquica",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.category",
                verbose_name="Parent category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly identifier (auto-generated) / Identificador amigável para URL (auto-gerado)",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#6c757d",
                help_text="Hex color code for badge display / Código de cor hex para exibição do badge",
                max_length=7,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Tag creation date / Data de criação da tag",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Tag name (unique) / Nome da tag (único)",
                max_length=50,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly identifier (auto-generated) / Identificador amigável para URL (auto-gerado)",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture / Foto de perfil",
                null=True,
                upload_to="avatars/%Y/%m/%d/",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="User biography (max 500 chars) / Biografia do usuário (máx 500 chars)",
                max_length=500,
                verbose_name="Biography",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="User's birth date / Data de nascimento do usuário",
                null=True,
                verbose_name="Birth date",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="User's city / Cidade do usuário",
                max_length=100,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="User's country / País do usuário",
                max_length=100,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Profile creation date / Data de criação do perfil",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if user is verified / Indica se usuário é verificado",
                verbose_name="Verified",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number with country code / Número de telefone com código do país",
                max_length=20,
                verbose_name="Phone",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last update date / Data da última atualização",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                help_text="Related Django user / Usuário Django relacionado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Personal website or portfolio / Website pessoal ou portfólio",
                verbose_name="Website",
            ),
        ),
    ]
